# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-24 04:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import filer.fields.folder


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
        ('filer', '0006_auto_20160623_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='djangocms_slider_sliderpluginmodel', serialize=False, to='cms.CMSPlugin')),
                ('animation', models.CharField(choices=[('fade', 'Fade'), ('slide', 'Slide')], default='fade', max_length=10)),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('anim_speed', models.PositiveIntegerField(default=500, help_text='Animation Speed (ms)', verbose_name='anim speed')),
                ('pause_time', models.PositiveIntegerField(default=3000, help_text='Pause time (ms)', verbose_name='pause time')),
                ('margin', models.PositiveIntegerField(default=0, help_text='Margin slide (px)', verbose_name='Margin slide')),
                ('min_slides', models.PositiveIntegerField(default=1, help_text='Minimal number slide', verbose_name='Min slide')),
                ('max_slides', models.PositiveIntegerField(default=4, help_text='Maximun number slide', verbose_name='Max slide')),
                ('width', models.PositiveIntegerField(help_text='Width of the plugin (px)', verbose_name='width')),
                ('height', models.PositiveIntegerField(help_text='Height of the plugin (px)', verbose_name='height')),
                ('arrows', models.BooleanField(default=True, help_text='Arrow buttons for navigation', verbose_name='arrows')),
                ('paginator', models.BooleanField(default=True, help_text='Paginator buttons for navigation', verbose_name='paginator')),
                ('album', filer.fields.folder.FilerFolderField(on_delete=django.db.models.deletion.CASCADE, to='filer.Folder', verbose_name='album')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
