# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-24 03:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_slider', '0002_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sliderpluginmodel',
            name='album',
        ),
        migrations.AddField(
            model_name='image',
            name='title',
            field=models.TextField(blank=True, null=True, verbose_name='title'),
        ),
    ]
